blank_issues_enabled: true
contact_links:
  - name: Discord server
    url: https://discord.gg/kphr9Z3XuW
    about: Feel free to join our Discord server for short questions/help and chatting with others
